"use client";

import { useState } from "react";
import { createLesson, updateLesson } from "@/app/admin/lessons/actions";

interface LessonFormProps {
    courseId: string;
    lessonHelper?: {
        id: string;
        title: string;
        content: string | null;
        video_url: string | null;
        order_index: number;
        is_free_preview: boolean;
    };
    onClose: () => void;
}

import VideoUpload from "../VideoUpload";

export default function LessonForm({ courseId, lessonHelper, onClose }: LessonFormProps) {
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [uploadedVideoUrl, setUploadedVideoUrl] = useState(lessonHelper?.video_url || "");

    // Auto-detect type
    const [videoType, setVideoType] = useState<'youtube' | 'upload'>(() => {
        if (lessonHelper?.video_url?.includes('/storage/v1/object/public/videos')) {
            return 'upload';
        }
        return 'youtube';
    });

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        setIsLoading(true);
        setError(null);

        const formData = new FormData(e.currentTarget);
        formData.append("course_id", courseId);

        // Ensure checkbox value is handled (if not generated by browser correctly)
        // Checkboxes only send 'on' if checked, nothing if unchecked. Handled in server action.

        let result;
        if (lessonHelper) {
            result = await updateLesson(lessonHelper.id, formData);
        } else {
            result = await createLesson(formData);
        }

        if (result?.error) {
            setError(result.error);
            setIsLoading(false);
        } else {
            onClose();
        }
    };

    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-xl shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
                <form onSubmit={handleSubmit} className="p-6">
                    <h2 className="text-xl font-bold text-gray-900 mb-6">
                        {lessonHelper ? "Edit Lesson" : "Add New Lesson"}
                    </h2>

                    {error && (
                        <div className="mb-6 p-4 bg-red-100 text-red-600 rounded-lg text-sm">
                            {error}
                        </div>
                    )}

                    <div className="space-y-6">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">Lesson Title</label>
                            <input
                                name="title"
                                defaultValue={lessonHelper?.title || ""}
                                required
                                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#2EBD59]/20 focus:border-[#2EBD59]"
                                placeholder="e.g. Introduction to Charts"
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">Video Content</label>

                            <div className="flex bg-gray-100 p-1 rounded-lg mb-4 w-fit">
                                <button
                                    type="button"
                                    onClick={() => setVideoType('youtube')}
                                    className={`px-4 py-1.5 text-sm font-medium rounded-md transition-all ${videoType === 'youtube' ? 'bg-white shadow text-gray-900' : 'text-gray-500 hover:text-gray-900'}`}
                                >
                                    YouTube / URL
                                </button>
                                <button
                                    type="button"
                                    onClick={() => setVideoType('upload')}
                                    className={`px-4 py-1.5 text-sm font-medium rounded-md transition-all ${videoType === 'upload' ? 'bg-white shadow text-gray-900' : 'text-gray-500 hover:text-gray-900'}`}
                                >
                                    Upload Video
                                </button>
                            </div>

                            {videoType === 'youtube' ? (
                                <input
                                    name="video_url"
                                    defaultValue={lessonHelper?.video_url || ""}
                                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#2EBD59]/20 focus:border-[#2EBD59]"
                                    placeholder="https://youtube.com/watch?v=..."
                                />
                            ) : (
                                <div>
                                    <input type="hidden" name="video_url" value={uploadedVideoUrl} />
                                    <VideoUpload
                                        value={uploadedVideoUrl}
                                        onChange={setUploadedVideoUrl}
                                        label=""
                                    />
                                </div>
                            )}
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">Order Index</label>
                            <input
                                type="number"
                                name="order_index"
                                defaultValue={lessonHelper?.order_index || 0}
                                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#2EBD59]/20 focus:border-[#2EBD59]"
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">Lesson Content (Markdown)</label>
                            <textarea
                                name="content"
                                defaultValue={lessonHelper?.content || ""}
                                rows={6}
                                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#2EBD59]/20 focus:border-[#2EBD59] font-mono text-sm"
                                placeholder="# Lesson Notes..."
                            />
                        </div>

                        <div className="flex items-center gap-3">
                            <input
                                type="checkbox"
                                name="is_free_preview"
                                id="is_free_preview"
                                defaultChecked={lessonHelper?.is_free_preview || false}
                                className="w-5 h-5 text-[#2EBD59] rounded focus:ring-[#2EBD59]"
                            />
                            <label htmlFor="is_free_preview" className="text-sm font-medium text-gray-700">
                                Free Preview (Accessible without purchase)
                            </label>
                        </div>
                    </div>

                    <div className="pt-8 flex items-center justify-end gap-4 border-t border-gray-100 mt-8">
                        <button
                            type="button"
                            onClick={onClose}
                            className="px-6 py-2 text-gray-600 hover:bg-gray-50 rounded-lg transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            disabled={isLoading}
                            className="px-6 py-2 bg-[#2EBD59] text-white rounded-lg hover:bg-[#26a34d] transition-colors disabled:opacity-50"
                        >
                            {isLoading ? "Saving..." : lessonHelper ? "Update Lesson" : "Add Lesson"}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
}
